# # -- 코드를 입력하세요
# # SELECT COUNT(DISTINCT NAME) count
# # FROM ANIMAL_INS
# # # WHERE NAME <> 'NULL'
# # #COUNT가 NULL은 자동으로 제거

# SELECT COUNT(DISTINCT NAME) count
# FROM ANIMAL_INS
# WHERE NAME <> "NULL"

SELECT COUNT(DISTINCT NAME) COUNT
FROM ANIMAL_INS 