SELECT INFO.CAR_ID, INFO.CAR_TYPE, FLOOR(INFO.DAILY_FEE * (100-PLAN.DISCOUNT_RATE) / 100 * 30) AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS INFO
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY ON INFO.CAR_ID = HISTORY.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON PLAN.CAR_TYPE = INFO.CAR_TYPE

WHERE (INFO.CAR_TYPE = "세단" OR INFO.CAR_TYPE = "SUV") 
    AND INFO.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE END_DATE >= "2022-11-01" AND START_DATE <= "2022-11-30")
    AND PLAN.DURATION_TYPE = "30일 이상"
    AND FLOOR(INFO.DAILY_FEE * (100-PLAN.DISCOUNT_RATE) / 100 * 30) between 500000 AND 2000000 
    
GROUP BY INFO.CAR_ID
# ORDER BY FEE DESC, INFO.CAR_TYPE ASC, INFO.CAR_ID DESC

